disabled_rules:
  - nesting
  
  - control_statement
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - leading_whitespace
  - legacy_constant
  - legacy_constructor
  - line_length
  - missing_docs
  - opening_brace
  - return_arrow_whitespace
  - statement_position
  - todo
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - valid_docs
  - variable_name
  - variable_name_max_length
  - variable_name_min_length
included:
  - Sources
excluded:
  - Pods