//
//  ElloDrawable.swift
//  Ello
//
//  Created by Colin T.A. Gray on 2/24/15.
//  Copyright (c) 2015 Ello. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class ElloDrawable : NSObject {

    //// Cache

    private struct Cache {
        static var color: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)
    }

    //// Colors

    public class var color: UIColor { return Cache.color }

    //// Drawing Methods

    public class func drawProfileIcon() {

        //// Bezier Drawing
        var bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(2.5, 47.7))
        bezierPath.addLineToPoint(CGPointMake(2.5, 72.5))
        bezierPath.addLineToPoint(CGPointMake(31.5, 72.5))
        bezierPath.addLineToPoint(CGPointMake(31.5, 47.7))
        bezierPath.addCurveToPoint(CGPointMake(16.5, 32.5), controlPoint1: CGPointMake(31.5, 47.7), controlPoint2: CGPointMake(31.5, 32.5))
        bezierPath.addCurveToPoint(CGPointMake(2.5, 47.7), controlPoint1: CGPointMake(1.5, 32.5), controlPoint2: CGPointMake(2.5, 47.7))
        bezierPath.closePath()
        ElloDrawable.color.setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()


        //// Oval Drawing
        var ovalPath = UIBezierPath(ovalInRect: CGRectMake(4.5, 3.5, 24, 24))
        ElloDrawable.color.setStroke()
        ovalPath.lineWidth = 1
        ovalPath.stroke()
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
